### ISSUE TITLE
can't find a way to contact forum moderator; cannot register

### ISSUE THREAD

**Issue by ssybesma** [on-prem/tinycorelinux-x86_64#1]
I tried 3 different browsers and the Captcha is broken.  No way for me to register.

I have 12 Intel Compute Sticks that this distro would be perfect for!!!
As long as it can handle UEFI and a 32-bit EFI shell and the OS is 64-bit, I should be able to use it and it would be a godsend.

Steve Sybesma
steve AT vwebr DOT net

**Comment by aw** [comment]
Sorry I have no relation to tinycore or its forum. You can try posting your [question here: https://github.com/tinycorelinux/Core-scripts](https://github.com/tinycorelinux/Core-scripts)
